#ifndef _BLOOP_CAN__H__
#define _BLOOP_CAN__H__

typedef enum _sending_module {
	RMS_SEND	= 0x00,
 	CCP_SEND	= 0x01,
	NAV_SEND	= 0x02,
	PV_SEND		= 0x04,
	BMS_SEND	= 0x07
} SENDING_MODULE;

#define SENDING_BIT_POS	4

typedef enum _receiving_module {
	RMS_REC_1		= 0x0C,
	RMS_REC_2		= 0x0A,
	CCP_REC			= 0x01,
	NAV_REC			= 0x02,
	PV_REC			= 0x03,
	BMS_REC			= 0x0E,
	ALL_REC			= 0x04,
	CCP_NAV_REC		= 0x05,
	CCP_PV_REC		= 0x06,
	NAV_PV_REC		= 0x07,
	CCP_NAV_PV_REC	= 0x08
} RECEIVING_MODULE;

typedef enum _message_type {
	CCP_FAULT				= 0,
	CCP_WARNING				= 1,
	LV_HEARTBEAT 			= 2,
	NAV_SOLENOID_COMMAND 	= 3,
	PV_MCU_ENABLE_COMMAND 	= 4,
	PV_FAULT 				= 5,
	PV_WARNING 				= 6,
	SHUTDOWN_CIRCUIT_STATUS	= 7,
	PV_PRESSURE				= 8,
	// RMS_ENABLE_HEARTBEAT
	// RMS_CLEAR_FAULTS
	// RMS_TORQUE
	// RMS_DISABLE_INVERTER
	// RMS_CAP_DISCHARGE
	NAV_FAULT				= 9,
	NAV_WARNING				= 10,
	TAPE_SHOULD_STOP		= 11,
	NAV_PRES_1				= 12,
	NAV_PRES_2				= 13,
	NAV_PRES_3				= 14,
	NAV_SOLENOID_1			= 15
	//OBDII_RETURN
} MESSAGE_TYPE;

#endif

